version:  '3'

services:
    poll:
        build: poll/
        restart: always
        ports: 
            - "5000:80"
        networks: 
            - "poll-tier"
    redis:
        image: "redis"
        ports: 
            - "6379"
        restart: always
        networks: 
            - "poll-tier"
            - "back-tier"
    worker:
        build: worker/
        restart: always
        networks:
            - "back-tier"
    db:
        image: "postgres"
        restart: always
        volumes:
            - db-data:/var/lib/postgres
            - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
        environment:
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "password"
        networks:
            - "result-tier"
            - "back-tier"
    result:
        build: result/
        depends_on: 
            - db
        ports: 
            - "5001:80"
        restart: always
        networks:
            - "result-tier"
networks:
    poll-tier: 
        driver: bridge
    result-tier: 
        driver: bridge
    back-tier: 
        driver: bridge

volumes:
    db-data: