apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-database-pv-volume
  namespace: default
  labels:
    type: local
    app: postgres-database
spec:
  storageClassName: manual
  capacity:
    storage: 512M
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-database-pv-claim
  labels:
    app: postgres-database
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512M
