---
    apiVersion: v1
    kind: ConfigMap
    metadata:
        name: redis-config-map
        namespace: default
        labels:
            app: redis
    data:
        REDIS_HOST: "redis.default.svc.cluster.local"